trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'B2C - Demo UI - BUILD'
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-az-adb2c-demoui-aca'
  location: 'eastus'
  containerImage: 'rutzscolabcr.azurecr.io/azadb2c/demo-web-ui:$(resources.pipeline.build.runName)'
  templateFile: '$(Pipeline.Workspace)/build/Infrastructure/ACA/main.bicep'
  acrName: 'rutzscolabcr'
  acrUsername: 'rutzscolabcr'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: '001'
    environment: 'CI'
    azureSubscription: ${{ variables.azureSubscription }}
    appName: 'rutzsco-az-adb2c-demoui'
    resourceGroupName: 'rutzsco-az-adb2c-demoui-aca'
    region: $(location)
    templateFile: $(templateFile)
    containerImage: $(containerImage)
    acrName: $(acrName)
    acrUsername: $(acrUsername)
    acrPassword: $(acrPassword)
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: '001'
    environment: 'CI'
    azureSubscription: ${{ variables.azureServiceConnection }}
    appName: 'rutzsco-az-adb2c-demoui-002'
    resourceGroupName: 'rutzsco-az-adb2c-demoui-aca-002'
    region: $(location)
    templateFile: $(templateFile)
    containerImage: $(containerImage)
    acrName: $(acrName)
    acrUsername: $(acrUsername)
    acrPassword: $(acrPassword)