trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'B2C - Demo UI - BUILD'
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-az-adb2c-demoui-aca'
  location: 'eastus'
  appName: 'rutzsco-az-adb2c-demoui'
  environment: 'ci'
  containerImage: 'rutzscolabcr.azurecr.io/azadb2c/demo-web-ui:$(resources.pipeline.build.runName)'
  templateFile: '$(Pipeline.Workspace)/build/Infrastructure/ACA/main.bicep'
  acrName: 'rutzscolabcr'
  acrUsername: 'rutzscolabcr'

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: 'ubuntu-latest'   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name $(resourceGroupName) --location $(location)  
                  az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters appName=$(appName) envName=$(environment) containerImage=$(containerImage) acrName=$(acrName) acrUsername=$(acrUsername) acrPassword=$(acrPassword) > outputs.json