parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureServiceConnection
  default: ''
- name: appName
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: templateFile
  default: ''  
- name: containerImage
  default: ''  
- name: acrName
  default: ''  
- name: acrUsername
  default: ''  
- name: acrPassword
  default: ''
- name: azureAdClientId
  default: ''
- name: azureAdSignUpSignInPolicyId
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
           steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.region }} 
                  az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file ${{ parameters.templateFile }} --parameters appName=${{ parameters.appName }} envName=${{ parameters.environment }} containerImage=${{ parameters.containerImage }} acrName=${{ parameters.acrName }} acrUsername=${{ parameters.acrUsername }} acrPassword=${{ parameters.acrPassword }} azureAdClientId=${{ parameters.azureAdClientId }} azureAdSignUpSignInPolicyId=${{ parameters.azureAdSignUpSignInPolicyId }} > outputs.json